browser: "chromium"          # Valid options are 'chromium', 'firefox', 'webkit'.
headless: false               # Set to True for headless mode, False for normal mode.
slow_motion: 300              # Adjust to slow down or speed up the actions, in milliseconds.
url: "QA"                     # Choose either 'QA' or 'DEV'.
token: "ronatoken"               # Choose either 'token1' or 'ronatoken'.
maximize_window: true         # Set True for maximize window, False for normal window

loading_numbers:
  #Regular Loading
  regular_loading_number_E2E: "0046707"
  regular_loading_number_error_handling: "0046707"
  regular_loading_number_E2E_half_discharge: "0046707"
  regular_loading_number_E2E_set_suspicious_notebook: "0046707"
  regular_loading_number_E2E_set_uncheck_notebook: "0046707"

  #AfterApeal Loading
  after_appeal_loading_number_E2E: "0045295"
  after_appeal_number_error_handling: "0045295"
  after_appeal_number_E2E_half_discharge: "0045295"
  after_appeal_number_E2E_set_suspicious_notebook: "0045295"
  after_appeal_number_E2E_set_uncheck_notebook: "0045295"