browser: "chromium"                     # options are 'chromium', 'firefox', 'webkit'.
headless: false                         # true for headless mode, false for normal mode.
slow_motion: 300                        # Adjust to slow down or speed up the actions, in milliseconds.
environment: "QA"                       # Choose either 'QA' or 'DEV'.
user_token: "Senior Evaluator"         # Choose either 'Senior Evaluator' or 'Regular Evaluator'.
permissions: "Senior Evaluator"        # Choose either 'Regular Evaluator' or 'Senior Evaluator'.
maximize_window: true                   # True for maximize window, False for normal window

loading_numbers:
  # Regular Loading
  regular_loading_E2E_num: "0045632"
  regular_loading_error_num: "0045612"
  regular_loading_half_discharge_num: "0045617"
  regular_loading_set_suspicious_num: "0045614"
  regular_loading_set_unchecked_num: "0045613"
  answer_law: "0045621"
  # MisMatch Loading
  misMatch_loading_E2E_num: "fill"
  misMatch_loading_set_suspicious_num: "fill"
  misMatch_loading_error_num: "fill"
  misMatch_loading_half_discharge_num: "fill"
  misMatch_loading_set_unchecked_num: "fill"
  # Senior Loading
  senior_loading_E2E_num: "0045517"
  senior_loading_set_suspicious_num: "fill"
  senior_loading_error_num: "fill"
  senior_loading_half_discharge_num: "fill"
  senior_loading_set_unchecked_num: "fill"
  # Suspicious Loading
  suspicious_loading_approve_num: "fill"
  suspicious_loading_denied_num: "fill"
  suspicious_loading_error_num: "fill"
  suspicious_loading_half_discharge_num: "fill"
  suspicious_loading_set_unchecked_num: "fill"
  # Sample After Evaluation Loading
  sample_loading_E2E_num: "fill"
  sample_loading_set_suspicious_num: "fill"
  sample_loading_error_num: "fill"
  sample_loading_half_discharge_num: "fill"
  sample_loading_set_unchecked_num: "fill"
  # After Appeal Loading
  appeal_loading_E2E_num: "fill"
  appeal_loading_error_num: "fill"
  appeal_loading_half_discharge_num: "fill"
  appeal_loading_set_suspicious_num: "fill"
  appeal_loading_set_unchecked_num: "fill"


